codecov:
  notify:
    after_n_builds: 1

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches:
    - main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%  # 허용 오차

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true
